#!/usr/bin/env bash

# arguments: process name, matchmaker data, desired output python file location and config
# e.g. ./parse-matchmaker-output S1 data/MatchingResult.dat python/s1_match.py data/S1Config.wl

wolframscript -file Parse.m $1 $2 $3 $4
