#!/usr/local/bin/python3

import os
import sys
import matchmakereft.libs.mm_offline as mm
from rich import print

particle_names = sys.argv[1:]
model_name = "_".join(particle_names)
particles = " ".join(particle_names)


def run_and_print(cmd):
    print("$ " + cmd)
    os.system(cmd)


# Run feynwrite
run_and_print(f"feynwrite {particles} > {model_name}.fr")

# Copy generic .symm and .gauge files
run_and_print(f"cp granada.symm {model_name}.symm")
run_and_print(f"cp granada.gauge {model_name}.gauge")
run_and_print(f"cp granada.red {model_name}.red")

# Run Matchmaker
mm.create_model(f"UnbrokenSM_BFM.fr {model_name}.fr")
mm.match_model_to_eft(f"{model_name}_MM SMEFT_Green_Bpreserving_MM")
mm.compute_rge_model_to_eft(f"{model_name}_MM SMEFT_Green_Bpreserving_MM")

# Check output
with open(f"{model_name}_MM/MatchingProblems.dat", "r") as problems_file:
    problems_text = problems_file.read()
    if problems_text.strip() == "problist = {}":
        print("\n[green]Matching performed without problems![/green] :thumbsup:")
    elif "ee" in problems_text:
        print(
            f"[yellow]Matchmaker reported problems with the matching, but this may be due to gamma_5.[/yellow] :thumbsdown:"
        )
    else:
        print(
            f"[red]Matchmaker reported problems with the matching.[/red] :thumbsdown:"
        )

with open(f"{model_name}_MM/MatchingResult.dat", "r") as results_file:
    results_text = results_file.read()
    mass_name = "M" + model_name.removeprefix("Granada")
    if mass_name in results_text.strip():
        print(
            f"[green]{mass_name} features in the matching results.[/green] :thumbsup:"
        )
    else:
        print(
            f"[red]{mass_name} does not feature in the matching results.[/red] :thumbsdown:"
        )
